# Generated by Django 4.1.7 on 2023-03-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_companytype_industry_user_business_name_user_cin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.companytype",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.industry",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.usertype",
            ),
        ),
    ]
