# Generated by Django 4.1.7 on 2023-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_business_name_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pan_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
