# Generated by Django 4.1.7 on 2023-04-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_phone_number_alter_user_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
    ]
