# Generated by Django 4.1.7 on 2023-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_name",
            field=models.CharField(max_length=80),
        ),
    ]
