# Generated by Django 4.1.7 on 2023-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
