# Generated by Django 4.1.7 on 2023-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_pan_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=564756367, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
