# Generated by Django 4.1.7 on 2023-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="username"
            ),
        ),
    ]
