# Generated by Django 4.1.7 on 2023-04-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
