# Generated by Django 4.1.7 on 2023-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="email address"
            ),
        ),
    ]
