# Generated by Django 4.1.7 on 2023-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="country",
            field=models.CharField(
                blank=True, default="India", max_length=100, null=True
            ),
        ),
    ]
