# Generated by Django 4.1.7 on 2023-08-11 04:18

import datetime
from django.db import migrations, models
import django.utils.timezone

import uuid
class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_user_is_premium_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="masked_pan",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=10,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="masked_pan",
            field=models.CharField(
                blank=True, null=True, max_length=10, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="pan_number",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pan_number",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
