# Generated by Django 4.1.7 on 2023-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_business_masked_pan_user_masked_pan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="masked_pan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="masked_pan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
