# Generated by Django 4.1.7 on 2023-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_business_masked_pan_alter_user_masked_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="last name"
            ),
        ),
    ]
