# Generated by Django 4.1.7 on 2023-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_business_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
