# Generated by Django 4.2.6 on 2024-02-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_is_email_verified_user_is_mobile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
