# Generated by Django 4.1.7 on 2023-03-28 16:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyPartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("total_outstanding", models.CharField(default="", max_length=40)),
                (
                    "on_time_Payment",
                    models.CharField(
                        choices=[
                            ("ZERO", 0),
                            ("TWOFIVE", 25),
                            ("FIFTY", 50),
                            ("SEVENFIVE", 75),
                            ("NINTY", 90),
                            ("HUNDRED", 100),
                        ],
                        default="ZERO",
                        max_length=80,
                    ),
                ),
                ("reachability", models.CharField(default="", max_length=255)),
                (
                    "Probabaility",
                    models.CharField(
                        choices=[
                            ("ZERO", 0),
                            ("TWOFIVE", 25),
                            ("FIFTY", 50),
                            ("SEVENFIVE", 75),
                            ("NINTY", 90),
                            ("HUNDRED", 100),
                        ],
                        default="ZERO",
                        max_length=80,
                    ),
                ),
                ("comments", models.CharField(default="", max_length=2000)),
                ("dso", models.CharField(default="", max_length=80)),
                ("pending_receivables", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_partner_assoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_partner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_partner_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_partner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
