# Generated by Django 4.1.7 on 2023-04-04 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_mypartner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
