# Generated by Django 4.1.7 on 2023-04-13 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_alter_mypartner_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="Probabaility",
            field=models.CharField(
                choices=[
                    (0, "0%"),
                    (1, "25%"),
                    (2, "50%"),
                    (3, "75%"),
                    (4, "90%"),
                    (5, "100%"),
                ],
                default="ZERO",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="on_time_Payment",
            field=models.CharField(
                choices=[
                    (0, "0%"),
                    (1, "25%"),
                    (2, "50%"),
                    (3, "75%"),
                    (4, "90%"),
                    (5, "100%"),
                ],
                default="ZERO",
                max_length=80,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mypartner",
            unique_together={("business_partner_main", "business_partner_assoc")},
        ),
    ]
