# Generated by Django 4.1.7 on 2023-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_mypartner_probabaility_mypartner_known_since_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypartner",
            name="is_existing_partner",
            field=models.BooleanField(default=False),
        ),
    ]
