# Generated by Django 4.1.7 on 2023-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_is_existing_partner_mypartner_is_business_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="reachability",
            field=models.CharField(
                choices=[(1, "Yes"), (2, "Difficult"), (0, "No")],
                default=0,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="recovery_probability",
            field=models.CharField(
                choices=[(1, "Yes"), (2, "Difficult"), (0, "No")],
                default=0,
                max_length=80,
            ),
        ),
    ]
