# Generated by Django 4.1.7 on 2023-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_mypartner_reachability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="on_time_Payment",
            field=models.CharField(
                choices=[
                    ("0", "0%"),
                    ("1", "25%"),
                    ("2", "50%"),
                    ("3", "75%"),
                    ("4", "90%"),
                    ("5", "100%"),
                ],
                default=0,
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="reachability",
            field=models.CharField(
                choices=[("1", "Yes"), ("2", "Difficult"), ("0", "No")],
                default=0,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="recovery_probability",
            field=models.CharField(
                choices=[("1", "Yes"), ("2", "Difficult"), ("0", "No")],
                default="0",
                max_length=80,
            ),
        ),
    ]
