# Generated by Django 4.1.7 on 2023-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_mypartner_reachability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="on_time_Payment",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0%"),
                    (1, "25%"),
                    (2, "50%"),
                    (3, "75%"),
                    (4, "90%"),
                    (5, "100%"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="reachability",
            field=models.IntegerField(
                blank=True, choices=[(1, "Yes"), (2, "Difficult"), (0, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="recovery_probability",
            field=models.IntegerField(
                blank=True, choices=[(1, "Yes"), (2, "Difficult"), (0, "No")], null=True
            ),
        ),
    ]
