# Generated by Django 4.1.7 on 2023-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_mypartner_on_time_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="dso",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
