# Generated by Django 4.1.7 on 2023-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_mypartner_dso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="score",
            field=models.IntegerField(
                choices=[
                    (5, "Excellent"),
                    (4, "Good"),
                    (3, "Delay payment"),
                    (2, "Defaulter"),
                    (1, "Intentional Fraud"),
                ]
            ),
        ),
    ]
