# Generated by Django 4.1.7 on 2023-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_mypartner_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypartner",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
