# Generated by Django 4.1.7 on 2023-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_mypartner_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="comments",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
    ]
