# Generated by Django 4.1.7 on 2023-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_mypartner_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
    ]
