# Generated by Django 4.1.7 on 2023-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_mypartner_dso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="dso",
            field=models.IntegerField(
                choices=[
                    (0, "0 Days"),
                    (1, ">60 Days"),
                    (2, ">90 Days"),
                    (3, ">120 Days"),
                    (4, ">150 Days"),
                    (5, ">180 Days"),
                    (6, ">360 Days"),
                ],
                default=0,
            ),
        ),
    ]
