# Generated by Django 4.1.7 on 2023-05-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0023_alter_mypartner_dso"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mypartner",
            options={"ordering": ("updated_on",)},
        ),
        migrations.CreateModel(
            name="ScoreDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pres_avg_score", models.FloatField(default=0)),
                ("prev_avg_score", models.FloatField(default=0)),
                ("raise_or_fall_percent", models.FloatField(default=0)),
                ("is_raised", models.BooleanField(default=False)),
                ("total_partners", models.IntegerField(default=0)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("updated_on",),
            },
        ),
    ]
