# Generated by Django 4.1.7 on 2023-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_mypartner_options_alter_scoredetails_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoredetails",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
