# Generated by Django 4.1.7 on 2023-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_scoredetails_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="score",
            field=models.IntegerField(
                choices=[
                    (5, "Excellent"),
                    (4, "Good"),
                    (3, "Average"),
                    (2, "Delay payment"),
                    (1, "Defaulter"),
                    (0, "Intentional Fraud"),
                ]
            ),
        ),
    ]
