# Generated by Django 4.1.7 on 2023-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_mypartner_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypartner",
            name="is_gst_paid",
            field=models.BooleanField(default=False),
        ),
    ]
