# Generated by Django 4.1.7 on 2023-05-31 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0028_mypartner_is_gst_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaisedDisputes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(max_length=2000)),
                ("response", models.TextField(blank=True, max_length=2000, null=True)),
                ("raised_on", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "assoc_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-raised_on",),
            },
        ),
    ]
