# Generated by Django 4.1.7 on 2023-05-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_raiseddisputes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raiseddisputes",
            old_name="assoc_partner",
            new_name="raised_on_user",
        ),
    ]
