# Generated by Django 4.1.7 on 2023-07-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_rename_assoc_partner_raiseddisputes_raised_on_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypartner",
            name="is_raised_dispute",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="raiseddisputes",
            name="resolved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="raiseddisputes",
            name="raised_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
