# Generated by Django 4.1.7 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_mypartner_is_raised_dispute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raiseddisputes",
            name="reason_option",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("NOT_HAVING_ANY_TRANS", "I am not having any transaction"),
                    ("HAVE_PENDING_CREDIT_NOTES", "I have pending credit notes"),
                    ("ALREADY_MADE_THE_PAYMENT", "I already made the payment"),
                    ("OTHERS", "Others"),
                ],
                null=True,
            ),
        ),
    ]
