# Generated by Django 4.1.7 on 2023-09-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypartner",
            name="capital",
            field=models.IntegerField(
                choices=[
                    (0, "Both are Good"),
                    (1, "Capital is good and Assest is not good"),
                    (2, "Assest is good and capital is not good "),
                    (3, "Both are not Good"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="mypartner",
            name="transaction_paid_ontime",
            field=models.IntegerField(
                choices=[
                    (0, "1 - 5"),
                    (1, "6 - 10"),
                    (2, "11 - 15"),
                    (3, "16 - 25"),
                    (4, "26 +"),
                ],
                default=0,
            ),
        ),
    ]
