# Generated by Django 4.1.7 on 2023-10-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0028_alter_business_masked_pan_alter_user_masked_pan"),
        ("api", "0036_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="score",
            field=models.IntegerField(
                choices=[
                    (10, "Excellent"),
                    (9, "Good"),
                    (7, "Average"),
                    (6, "Delay of Service"),
                    (5, "Lack of After Sales Service"),
                    (4, "Delay payment"),
                    (3, "No Show After Payment"),
                    (2, "Defaulter"),
                    (1, "Intentional Fraud"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_amount", models.BigIntegerField()),
                ("transaction_id", models.CharField(max_length=255)),
                ("is_success", models.BooleanField(default=False)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="users.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-payment_date",),
            },
        ),
    ]
