# Generated by Django 4.1.7 on 2023-11-13 06:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_gstindetails_mypartner_assets_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTinDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incorporation_date", models.DateField()),
                ("company", models.CharField(max_length=256)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("state", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=6)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=500)),
                ("fullname", models.CharField(max_length=200)),
                ("industry", jsonfield.fields.JSONField(default=[])),
            ],
        ),
    ]
