# Generated by Django 4.1.7 on 2023-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_mypartner_legal_proceedings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
