# Generated by Django 4.1.7 on 2023-11-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="validity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="description",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
