# Generated by Django 4.1.7 on 2023-11-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_subscription_validity_alter_subscription_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.subscription",
            ),
            preserve_default=False,
        ),
    ]
