# Generated by Django 4.1.7 on 2023-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_payments_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypartner",
            name="assets",
            field=models.IntegerField(
                choices=[(0, "Yes"), (1, "Moderate"), (2, "No")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="capital",
            field=models.IntegerField(
                choices=[(0, "Yes"), (1, "Moderate"), (2, "No")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="dso",
            field=models.IntegerField(
                choices=[
                    (0, "30 Days"),
                    (1, "60 Days"),
                    (2, "90 Days"),
                    (3, "120 Days"),
                    (4, "150 Days"),
                    (5, "180 Days"),
                    (6, "1 Year"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="on_time_Payment",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "100%"),
                    (1, "90%"),
                    (2, "75%"),
                    (3, "50%"),
                    (4, "25%"),
                    (5, "0%"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="reachability",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Yes"),
                    (1, "Yes with multiple attempts"),
                    (2, "Difficult"),
                    (3, "No"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="recovery_probability",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Yes"),
                    (1, "Yes with multiple attempts"),
                    (2, "Difficult"),
                    (3, "No"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="score",
            field=models.IntegerField(
                choices=[
                    (10, "Excellent"),
                    (9, "Good"),
                    (8, "Average"),
                    (7, "Service Delay"),
                    (6, "Lack of Post-Sale Support"),
                    (5, "Market Disruption/Dispute/UnderCutting "),
                    (4, "Payment Delay"),
                    (3, "Non-Delivery After Payment"),
                    (2, "Payment Defaul"),
                    (1, "Fraudulent Activity"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="total_outstanding",
            field=models.IntegerField(
                choices=[
                    (0, "<2 Lakh"),
                    (1, "2-5 Lakh"),
                    (2, "5-10 Lakh"),
                    (3, "10-20 Lakh"),
                    (4, "20-50 Lakh"),
                    (5, "50-1 Cr"),
                    (6, ">1 Cr"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="mypartner",
            name="transaction_paid_ontime",
            field=models.IntegerField(
                choices=[
                    (0, "1 - 5"),
                    (1, "6 - 10"),
                    (2, "11 - 15"),
                    (3, "16 - 25"),
                    (4, "25 +"),
                ],
                default=0,
            ),
        ),
    ]
