# Generated by Django 4.2.6 on 2024-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_mypartner_assets_alter_mypartner_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypartner',
            name='dso',
            field=models.IntegerField(choices=[(0, '0 Days'), (1, '30 Days'), (2, '60 Days'), (3, '90 Days'), (4, '180 Days'), (5, '365 Days'), (6, '730 Days')], default=0),
        ),
        migrations.AlterField(
            model_name='mypartner',
            name='pending_receivables',
            field=models.IntegerField(choices=[(0, '0'), (1, '<2 Lakh'), (2, '2-5 Lakh'), (3, '5-10 Lakh'), (4, '10-20 Lakh'), (5, '20-50 Lakh'), (6, '50-1 Cr'), (7, '>1 Cr')], default=0),
        ),
        migrations.AlterField(
            model_name='mypartner',
            name='total_outstanding',
            field=models.IntegerField(choices=[(0, '0'), (1, '<2 Lakh'), (2, '2-5 Lakh'), (3, '5-10 Lakh'), (4, '10-20 Lakh'), (5, '20-50 Lakh'), (6, '50-1 Cr'), (7, '>1 Cr')], default=0),
        ),
    ]
