# Generated by Django 4.1.7 on 2023-08-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=100, verbose_name="Payment Id"),
                ),
                ("order_id", models.CharField(max_length=100, verbose_name="Order Id")),
                (
                    "signature",
                    models.CharField(max_length=100, verbose_name="Signature"),
                ),
                ("amount", models.IntegerField(verbose_name="Amount")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True, max_length=500, null=True)),
                ("is_subscribed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
